version: '3'

services:
  dynamodb-admin:
    image: instructure/dynamo-local-admin
    hostname: dynamodb-local
    container_name: dynamodb-local
    ports:
      - '8000:8000'
  dynamodb-table:
    build: infrastructure/dev
    hostname: dynamodb-table
    container_name: dynamodb-table
    environment:
      WAIT_HOSTS: dynamodb-admin:8000
  localstack:
    image: localstack/localstack
    container_name: localstack
    network_mode: bridge
    ports:
      - 4566:4566
      - '${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}'
    environment:
      - SERVICES=s3,events
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${PORT_WEB_UI- }
    volumes:
      - 'localstack-vol:/tmp/localstack'

volumes:
  localstack-vol:
